### ISSUE TITLE
Tag 1.2.1 release

### ISSUE THREAD

**Issue by alucryd** [nix-community/acpi_call#13]
Hy guys, any chance of tagging a 1.2.1 release ? We'd like to switch to this repo over the unmaintained one for the Arch Linux package. Thanks in advance.

**Comment by teleshoes** [comment]
just to be clear, you just want me to tag the current master? no features needed to do so?
is there a repo for the arch linux package to compare and make sure this has everything?

**Comment by teleshoes** [comment]
(and why not 1.2.0? is it already 1.2* in arch?)

**Comment by alucryd** [comment]
Well your https://github.com/nix-community/acpi_call/blob/master/VERSION file mentions 1.2.1 so 1.2.0 didn't seem to make sense.

Master is perfectly fine if you consider it stable enough to be tagged. Here are both our packages built from the old upstream:
* https://www.archlinux.org/packages/community/x86_64/acpi_call/
* https://www.archlinux.org/packages/community/x86_64/acpi_call-dkms/

You can see the file list on each page, or you can download the packages from the right links, they're just xz archives.

**Comment by teleshoes** [comment]
hey good point. yea master has been sitting for a few months with no bug reports, and the 64bit fix for size_t is somewhat important. a release tag matching the version in the pkgfile, at least, seems in order

**Comment by teleshoes** [comment]
thanks!

**Comment by alucryd** [comment]
Thank you!
