### ISSUE TITLE
Linux 5.13: TLP and acpi_call freeze the computer

### ISSUE THREAD

**Issue by torvic9** [nix-community/acpi_call#15]
On Linux 5.13, I get a complete freeze with installed acpi_call whenever TLP starts up or using any of the `tlp` commands.
No issues **without** acpi_call, and also no issues on Linux 5.12 **with** acpi_call.
Due to the complete freeze, I do not have any logs or error messages.

Note that I'm not using NixOS but EndeavourOS/Arch.
Not sure if this is a problem with acpi_call, the kernel or TLP.

**Comment by alexw65500** [comment]
Linux 5.13 make lseek support mandatory for the proc FS.
You should get something like that in dmesg:
`kernel: BUG: kernel NULL pointer dereference, address: 0000000000000000`

I've uploaded a proposed fix [here](https://bugs.gentoo.org/801214)

**Comment by teleshoes** [comment]
looks good, thanks. can you pr it? ill grab an rc kernel and test+merge when i get a sec

**Comment by alexw65500** [comment]
I've now made a PR out of the patch. One you merge it I'll delete the then useless fork.

**Comment by teleshoes** [comment]
fixed in #16. thx again!

**Comment by danfos** [comment]
I was able to trigger this problem on Opensuse Tumbleweed, good to see it has been fixed!

Would it be possible create a new Tag with this fix in? That would make it easier packages based on it.

**Comment by teleshoes** [comment]
sure, tagged v1.2.2

**Comment by danfos** [comment]
@teleshoes: Thanks!
