### ISSUE TITLE
Tag v1.2.2 but VERSION still at 1.2.1

### ISSUE THREAD

**Issue by timkgh** [nix-community/acpi_call#20]
https://github.com/nix-community/acpi_call/blob/v1.2.2/VERSION

Should it be bumped to 1.2.2?

**Comment by teleshoes** [comment]
hey sorry about this. forgot to update it before tagging, and then missed this issue. thanks timkgh and szero

**Comment by teleshoes** [comment]
updated VERSION and updated the tag :/
